export component SelectorModal inherits Rectangle {
    in-out property <bool> modal-visible: false;
    in property <string> title: "";

    callback close();

    visible: root.modal-visible;

    background-overlay := Rectangle {
        width: 100%;
        height: 100%;
        background: #00000080;

        TouchArea {
            clicked => { root.close(); }
        }
    }

    modal-content := Rectangle {
        width: min(220px, root.width - 60px);
        height: min(360px, root.height - 40px);
        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;

        background: white;
        border-radius: 15px;
        border-width: 2px;
        border-color: #333333;
        drop-shadow-blur: 10px;
        drop-shadow-color: #00000040;

        TouchArea {
            clicked => { }
        }

        VerticalLayout {
            padding: 25px;
            spacing: 20px;

            if root.title != "": Text {
                text: root.title;
                font-size: 20px;
                font-weight: 700;
                horizontal-alignment: center;
                color: #333333;
            }

            VerticalLayout {
                spacing: 18px;
                @children
            }
        }
    }
}
