[alias]
xtask = 'run -p xtask --'
unit-test = 'test -q -p lib --target=x86_64-unknown-linux-gnu --features emulation'
sim = 'run -p simulation --target=x86_64-unknown-linux-gnu'
unit-test-mac = 'test -q -p lib --target=aarch64-apple-darwin --features emulation'
check-chip = 'check -p chip --target=xtensa-esp32s3-none-elf -Zbuild-std=core,alloc'
build-chip = 'build -p chip --target=xtensa-esp32s3-none-elf -Z build-std=core,alloc'
build-chip-release = 'build -p chip --release --target=xtensa-esp32s3-none-elf -Z build-std=core,alloc'
lint = 'clippy -p lib --target=x86_64-unknown-linux-gnu --features emulation -- -D warnings'
flash-chip = 'run -p chip --target=xtensa-esp32s3-none-elf --release -Z build-std=core,alloc'

[target.'cfg(target_arch = "xtensa")']
runner    = "espflash flash --monitor --partition-table chip/partition_table.csv --ignore_app_descriptor -a hard-reset"
rustflags = [
  # GNU LD
  "-C", "link-arg=-Wl,-Tlinkall.x,-Map=target/output.map",
  "-Z", "emit-stack-sizes",
  # "-C", "link-arg=-nostartfiles",
]

[target.'cfg(target_arch = "x86_64")']
rustflags = [
#   # GNU LD
  # "-C", "link-arg=-Wl,-Tlinkall.x",
  # "-C", "link-arg=-nostartfiles",
]

[target.'cfg(target_arch = "aarch64")']
rustflags = [
  # GNU LD
  # "-C", "link-arg=-Wl,-Tlinkall.x",
  # "-C", "link-arg=-nostartfiles",
]

# CHRONO_TZ_TIMEZONE_FILTER currently just supports America/Los_Angeles,
# because embedding the full tz database is too space-intensive atm (600kB).
# This isn't great, but I need to do a time zone audit to improve usability
# without bloating the binary size too much
[env]
CHRONO_TZ_TIMEZONE_FILTER = "^(America/Los_Angeles)"
# CHRONO_TZ_TIMEZONE_FILTER = "^(Africa|America|Antarctica|Arctic|Asia|Atlantic|Australia|Europe|Indian|Pacific)/"
ESP_HAL_CONFIG_PSRAM_MODE = "octal"
ESP_HAL_CONFIG_PLACE_RMT_DRIVER_IN_RAM = "true"
ESP_HAL_CONFIG_PLACE_SPI_MASTER_DRIVER_IN_RAM = "true"
