[alias]
b = "build --release"
r = "run --release -- "
c = "check --release"

[build]
target    = "xtensa-esp32s3-none-elf"

[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
  "-C", "link-arg=-Trom_functions.x",
]

[target.'cfg(target_arch = "xtensa")']
runner    = "espflash flash --monitor --partition-table partition_table.csv"
rustflags = [
  # GNU LD
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
  # "-C", "link-arg=-Trom_functions.x",

  # LLD
  # "-C", "link-arg=-Tlinkall.x",
  # "-C", "linker=rust-lld",
]

[env]
ESP_LOGLEVEL = "info"

[unstable]
build-std = ["alloc", "core"]
